// <copyright file="MunicipalityDOTest.PollingStationsSet.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using System.Collections.Generic;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Framework.Moles;
using System.Collections.Generic.Moles;
using Microsoft.Pex.Framework;
using Microsoft.Moles.Framework;
using System.Data.Linq;
using Microsoft.Pex.Engine.Exceptions;

namespace DBComm.DBComm.DO
{
    public partial class MunicipalityDOTest
    {
[TestMethod]
[PexGeneratedBy(typeof(MunicipalityDOTest))]
public void PollingStationsSet556()
{
    MunicipalityDO municipalityDO;
    municipalityDO =
      new MunicipalityDO(default(uint?), (string)null, (string)null, (string)null);
    PollingStationDO[] pollingStationDOs = new PollingStationDO[3];
    this.PollingStationsSet
        (municipalityDO, (ICollection<PollingStationDO>)pollingStationDOs);
    Assert.IsNotNull((object)municipalityDO);
    Assert.IsNotNull(municipalityDO.PollingStations);
    Assert.IsNull((object)(municipalityDO.Id));
    Assert.AreEqual<string>((string)null, municipalityDO.Address);
    Assert.AreEqual<string>((string)null, municipalityDO.City);
    Assert.AreEqual<string>((string)null, municipalityDO.Name);
}
[TestMethod]
[PexGeneratedBy(typeof(MunicipalityDOTest))]
public void PollingStationsSet900()
{
    MunicipalityDO municipalityDO;
    municipalityDO =
      new MunicipalityDO(default(uint?), (string)null, (string)null, (string)null);
    PollingStationDO[] pollingStationDOs = new PollingStationDO[2];
    this.PollingStationsSet
        (municipalityDO, (ICollection<PollingStationDO>)pollingStationDOs);
    Assert.IsNotNull((object)municipalityDO);
    Assert.IsNotNull(municipalityDO.PollingStations);
    Assert.IsNull((object)(municipalityDO.Id));
    Assert.AreEqual<string>((string)null, municipalityDO.Address);
    Assert.AreEqual<string>((string)null, municipalityDO.City);
    Assert.AreEqual<string>((string)null, municipalityDO.Name);
}
[TestMethod]
[PexGeneratedBy(typeof(MunicipalityDOTest))]
[Ignore]
[PexDescription("the test state was: duplicate path")]
public void PollingStationsSetThrowsOverflowException877()
{
    using (PexChooseBehavedBehavior.Setup())
    {
      MunicipalityDO municipalityDO;
      SICollection01<PollingStationDO> sICollection01;
      municipalityDO =
        new MunicipalityDO(default(uint?), (string)null, (string)null, (string)null);
      sICollection01 = new SICollection01<PollingStationDO>();
      sICollection01.CopyToTArrayInt32 =
        PexChoose.CreateDelegate<MolesDelegates.Action<PollingStationDO[], int>>();
      IPexChoiceRecorder choices = PexChoose.Replay.Setup();
      choices.NextSegment(2).DefaultSession
          .At(0, 
                                            "sICollection01`1.System.Collections.Generic.ICollection`1<!0>.get_Count", 
                                            (object)(-2147483646));
      this.PollingStationsSet
          (municipalityDO, (ICollection<PollingStationDO>)sICollection01);
    }
}
[TestMethod]
[PexGeneratedBy(typeof(MunicipalityDOTest))]
public void PollingStationsSet862()
{
    using (PexChooseBehavedBehavior.Setup())
    {
      MunicipalityDO municipalityDO;
      SICollection01<PollingStationDO> sICollection01;
      municipalityDO =
        new MunicipalityDO(default(uint?), (string)null, (string)null, (string)null);
      sICollection01 = new SICollection01<PollingStationDO>();
      sICollection01.CountGet = PexChoose.CreateDelegate<MolesDelegates.Func<int>>();
      this.PollingStationsSet
          (municipalityDO, (ICollection<PollingStationDO>)sICollection01);
      Assert.IsNotNull((object)municipalityDO);
      Assert.IsNotNull(municipalityDO.PollingStations);
      Assert.IsNull((object)(municipalityDO.Id));
      Assert.AreEqual<string>((string)null, municipalityDO.Address);
      Assert.AreEqual<string>((string)null, municipalityDO.City);
      Assert.AreEqual<string>((string)null, municipalityDO.Name);
    }
}
[TestMethod]
[PexGeneratedBy(typeof(MunicipalityDOTest))]
public void PollingStationsSet798()
{
    MunicipalityDO municipalityDO;
    municipalityDO =
      new MunicipalityDO(default(uint?), (string)null, (string)null, (string)null);
    PollingStationDO[] pollingStationDOs = new PollingStationDO[1];
    this.PollingStationsSet
        (municipalityDO, (ICollection<PollingStationDO>)pollingStationDOs);
    Assert.IsNotNull((object)municipalityDO);
    Assert.IsNotNull(municipalityDO.PollingStations);
    Assert.IsNull((object)(municipalityDO.Id));
    Assert.AreEqual<string>((string)null, municipalityDO.Address);
    Assert.AreEqual<string>((string)null, municipalityDO.City);
    Assert.AreEqual<string>((string)null, municipalityDO.Name);
}
[TestMethod]
[PexGeneratedBy(typeof(MunicipalityDOTest))]
public void PollingStationsSet623()
{
    MunicipalityDO municipalityDO;
    municipalityDO =
      new MunicipalityDO(default(uint?), (string)null, (string)null, (string)null);
    PollingStationDO[] pollingStationDOs = new PollingStationDO[0];
    this.PollingStationsSet
        (municipalityDO, (ICollection<PollingStationDO>)pollingStationDOs);
    Assert.IsNotNull((object)municipalityDO);
    Assert.IsNotNull(municipalityDO.PollingStations);
    Assert.IsNull((object)(municipalityDO.Id));
    Assert.AreEqual<string>((string)null, municipalityDO.Address);
    Assert.AreEqual<string>((string)null, municipalityDO.City);
    Assert.AreEqual<string>((string)null, municipalityDO.Name);
}
[TestMethod]
[PexGeneratedBy(typeof(MunicipalityDOTest))]
public void PollingStationsSet820()
{
    MunicipalityDO municipalityDO;
    municipalityDO =
      new MunicipalityDO(default(uint?), (string)null, (string)null, (string)null);
    EntitySet<PollingStationDO> entitySet = new EntitySet<PollingStationDO>();
    this.PollingStationsSet
        (municipalityDO, (ICollection<PollingStationDO>)entitySet);
    Assert.IsNotNull((object)municipalityDO);
    Assert.IsNotNull(municipalityDO.PollingStations);
    Assert.IsNull((object)(municipalityDO.Id));
    Assert.AreEqual<string>((string)null, municipalityDO.Address);
    Assert.AreEqual<string>((string)null, municipalityDO.City);
    Assert.AreEqual<string>((string)null, municipalityDO.Name);
}
[TestMethod]
[PexGeneratedBy(typeof(MunicipalityDOTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void PollingStationsSetThrowsContractException152()
{
    try
    {
      MunicipalityDO municipalityDO;
      municipalityDO =
        new MunicipalityDO(default(uint?), (string)null, (string)null, (string)null);
      this.PollingStationsSet(municipalityDO, (ICollection<PollingStationDO>)null);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
    }
}
